version: '3'

services:
  db:
    image: postgres:14
    container_name: diary_pg
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "super-user"
      POSTGRES_PASSWORD: "dummyPass"
      POSTGRES_DB: "diary_app"

volumes:
  db-store: